const ChatActionTypes = {
  FETCH_CHAT_CONTENT_START: 'FETCH_CHAT_CONTENT_START',
  FETCH_CHAT_CONTENT_SUCCESS: 'FETCH_CHAT_CONTENT_SUCCESS',
  FETCH_FAILURE: 'FETCH_FAILURE',
  FETCH_CONVERSATIONS_START: 'FETCH_CONVERSATIONS_START',
  FETCH_CONVERSATIONS_SUCCESS: 'FETCH_CONVERSATIONS_SUCCESS',
  FETCH_SUGGESTED_START: 'FETCH_SUGGESTED_START',
  FETCH_SUGGESTED_SUCCESS: 'FETCH_SUGGESTED_SUCCESS',
  CREATE_CONVERSATION_START: 'CREATE_CONVERSATION_START',
  CREATE_CONVERSATION_SUCCESS: 'CREATE_CONVERSATION_SUCCESS',
};

export default ChatActionTypes;
