const ChatActionTypes = {
  FETCH_CHAT_CONTENT_START: 'FETCH_CHAT_CONTENT_START',
  FETCH_CHAT_CONTENT_SUCCESS: 'FETCH_CHAT_CONTENT_SUCCESS',
  FETCH_CHAT_CONTENT_FAILURE: 'FETCH_CHAT_CONTENT_FAILURE',
  FETCH_CONVERSATIONS_START: 'FETCH_CONVERSATIONS_START',
  FETCH_CONVERSATIONS_SUCCESS: 'FETCH_CONVERSATIONS_SUCCESS',
  FETCH_CONVERSATIONS_FAILURE: 'FETCH_CONVERSATIONS_FAILURE',
  FETCH_SUGGESTED_USERS_START: 'FETCH_SUGGESTED_USERS_START',
  FETCH_SUGGESTED_USERS_SUCCESS: 'FETCH_SUGGESTED_USERS_SUCCESS',
  FETCH_SUGGESTED_USERS_FAILURE: 'FETCH_SUGGESTED_USERS_FAILURE',
  CREATE_CONVERSATION_START: 'CREATE_CONVERSATION_START',
  CREATE_CONVERSATION_SUCCESS: 'CREATE_CONVERSATION_SUCCESS',
  CREATE_CONVERSATION_FAILURE: 'CREATE_CONVERSATION_FAILURE',
  SEND_MESSAGE_START: 'SEND_MESSAGE_START',
  SEND_MESSAGE_SUCCESS: 'SEND_MESSAGE_SUCCESS',
  SEND_MESSAGE_FAILURE: 'SEND_MESSAGE_FAILURE'
};

export default ChatActionTypes;
