const ChatActionTypes = {
  FETCH_CHAT_CONTENT_START: 'FETCH_CHAT_CONTENT_START',
  FETCH_CHAT_CONTENT_SUCCESS: 'FETCH_CHAT_CONTENT_SUCCESS',
  FETCH_CHAT_CONTENT_FAILURE: 'FETCH_CHAT_CONTENT_FAILURE',
  FETCH_CONVERSATIONS_START: 'FETCH_CONVERSATIONS_START',
  FETCH_CONVERSATIONS_SUCCESS: 'FETCH_CONVERSATIONS_SUCCESS',
  FETCH_CONVERSATIONS_FAILURE: 'FETCH_CONVERSATIONS_FAILURE',
  FETCH_RANDOM_START: 'FETCH_RANDOM',
  FETCH_RANDOM_SUCCESS: 'FETCH_RANDOM_SUCCESS',
  FETCH_RANDOM_FAILURE: 'FETCH_RANDOM_FAILURE',
  CREATE_CONVERSASION_START: 'CREATE_CONVERSASION_START',
  CREATE_CONVERSASION_SUCCESS: 'CREATE_CONVERSASION_SUCCESS',
  CREATE_CONVERSASION_FAILURE: 'CREATE_CONVERSASION_FAILURE'
};

export default ChatActionTypes;
