const ProfileActionTypes = {
  FETCH_HOBBY_START: 'FETCH_HOBBY_START',
  FETCH_HOBBY_SUCCESS: 'FETCH_HOBBY_SUCCESS',
  FETCH_HOBBY_FAILURE: 'FETCH_HOBBY_FAILURE',
  FETCH_ISSUES_START: 'FETCH_ISSUES_START',
  FETCH_ISSUES_SUCCESS: 'FETCH_ISSUES_SUCCESS',
  FETCH_ISSUES_FAILURE: 'FETCH_ISSUES_FAILURE',
  UPDATE_PROFILE_START: 'UPDATE_PROFILE_START',
  UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_SUCCESS',
  UPDATE_PROFILE_FAILURE: 'UPDATE_PROFILE_FAILURE'
};

export default ProfileActionTypes;
