const ModalActionTypes = {
  TOGGLE_FIND_FRIENDS_MODAL_OPENED: 'TOGGLE_FIND_FRIENDS_MODAL_OPENED',
  TOGGLE_HOBBIES_MODAL_OPENED: 'TOGGLE_HOBBIES_MODAL_OPENED',
  TOGGLE_TOPICS_MODAL_OPENED: 'TOGGLE_TOPICS_MODAL_OPENED'
};

export default ModalActionTypes;
