const UserActionTypes = {
  GET_CURRENT_USER: 'GET_CURRENT_USER',
  EMAIL_SIGN_IN_START: 'EMAIL_SIGN_IN_START',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
  SIGN_OUT_START: 'SIGN_OUT_START',
  SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
  SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',
  SIGN_UP_START: 'SIGN_UP_START',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
  FETCH_HOBBIES_START: 'FETCH_HOBBIES_START',
  FETCH_HOBBIES_SUCCESS: 'FETCH_HOBBIES_SUCCESS',
  FETCH_HOBBIES_FAILURE: 'FETCH_HOBBIES_FAILURE',
  FETCH_TOPICS_START: 'FETCH_TOPICS_START',
  FETCH_TOPICS_SUCCESS: 'FETCH_TOPICS_SUCCESS',
  FETCH_TOPICS_FAILURE: 'FETCH_TOPICS_FAILURE',
  UPDATE_PROFILE_START: 'UPDATE_PROFILE_START',
  UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_SUCCESS',
  UPDATE_PROFILE_FAILURE: 'UPDATE_PROFILE_FAILURE',
  UPDATE_PROFILE_AVATAR_START: 'UPDATE_PROFILE_AVATAR_START',
  UPDATE_PROFILE_AVATAR_SUCCESS: 'UPDATE_PROFILE_AVATAR_SUCCESS',
  UPDATE_PROFILE_AVATAR_FAILURE: 'UPDATE_PROFILE_AVATAR_FAILURE'
};

export default UserActionTypes;
